name: lpr2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - opencv
  - matplotlib
  - scikit-learn
  - scikit-image
  - pandas
  - pillow
  - scipy
  - pytesseract
  - tesserocr
  - ipykernel
  - seaborn
  - torch-ema
  - diffusers
  - pydantic-core
  - tqdm
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch
    - torchvision
    - torchaudio
    - mlflow
    - pytorch-msssim
    - psutil
    - pynvml
    - pydantic
